<?php

namespace Database\Seeders;

use App\Models\PaymentMethod;
use Illuminate\Database\Seeder;

class PaymentMethodSeeder extends Seeder
{
    public function run(): void
    {
        $methods = [
            // 🇪🇬 EGYPT
            [
                'name' => 'فودافون كاش',
                'sub_name' => 'VF-CASH',
                'code' => 'vodafone_cash',
                'country' => 'egypt',
                'country_name' => 'تحويل مصر',
                'type' => 'manual',
                'currency' => 'EGY',
                'min_amount' => 50.00,
                'max_amount' => 50000.00,
                'fixed_fee' => 0.00,
                'percent_fee' => 0.00,
                'account_number' => '01025515743',
                'note' => 'برجاء كتابه رقم العمليه لضمان التنفيذ 0 ثانيه',
                'instruction' => 'أقل تحويل 50 ج، يتم مراجعة الإيصال وإيداع الرصيد في محفظتك فوراً.',
                'account_details' => ['wallet_number' => '01025515743', 'account_name' => 'Emperor VF-Cash'],
                'instructions' => [
                    'ar' => 'قم بتحويل المبلغ المطلوب إلى رقم فودافون كاش الموضح، ثم ارفع صورة الإيصال أو أدخل رقم المحفظة المحول منها.',
                    'en' => 'Transfer the amount to the Vodafone Cash wallet number and attach the payment screenshot.',
                ],
                'is_active' => true,
                'allow_deposit' => true,
                'allow_withdrawal' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'انستا بي (InstaPay)',
                'sub_name' => 'انستا بي',
                'code' => 'instapay',
                'country' => 'egypt',
                'country_name' => 'تحويل مصر',
                'type' => 'manual',
                'currency' => 'EGY',
                'min_amount' => 50.00,
                'max_amount' => 100000.00,
                'fixed_fee' => 0.00,
                'percent_fee' => 0.00,
                'account_number' => 'ahmedsalah@instapay',
                'note' => 'ahmedsalah',
                'instruction' => 'حول عبر انستاباي إلى العنوان المعرف أو رقم الهاتف ثم ارفع سكرين شوت الإيصال.',
                'account_details' => ['ipa_handle' => 'ahmedsalah@instapay', 'account_name' => 'Ahmed Salah'],
                'instructions' => [
                    'ar' => 'قم بالتحويل عبر تطبيق انستاباي إلى العنوان المعرف أو رقم الحساب، ثم ارفع إيصال التحويل.',
                    'en' => 'Transfer via InstaPay to the handle/account and upload receipt.',
                ],
                'is_active' => true,
                'allow_deposit' => true,
                'allow_withdrawal' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'اتصالات كاش',
                'sub_name' => 'اتصالات كاش',
                'code' => 'etisalat_cash',
                'country' => 'egypt',
                'country_name' => 'تحويل مصر',
                'type' => 'manual',
                'currency' => 'EGY',
                'min_amount' => 50.00,
                'max_amount' => 50000.00,
                'fixed_fee' => 0.00,
                'percent_fee' => 0.00,
                'account_number' => '01123456789',
                'note' => 'سيتم قبول المبلغ بعد المراجعه من قبل الادارة',
                'instruction' => 'أقل تحويل 50 ج، التحويل متاح 24/7 عبر محفظة اتصالات كاش.',
                'account_details' => ['wallet_number' => '01123456789'],
                'is_active' => true,
                'allow_deposit' => true,
                'allow_withdrawal' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'أورنج كاش',
                'sub_name' => 'أورنج كاش',
                'code' => 'orange_cash',
                'country' => 'egypt',
                'country_name' => 'تحويل مصر',
                'type' => 'manual',
                'currency' => 'EGY',
                'min_amount' => 50.00,
                'max_amount' => 50000.00,
                'fixed_fee' => 0.00,
                'percent_fee' => 0.00,
                'account_number' => '01234567890',
                'note' => 'برجاء كتابه رقم العمليه لضمان التنفيذ 0 ثانيه',
                'instruction' => 'أقل تحويل 50 ج، سيتم إضافة الرصيد تلقائياً بعد الفحص.',
                'account_details' => ['wallet_number' => '01234567890'],
                'is_active' => true,
                'allow_deposit' => true,
                'allow_withdrawal' => true,
                'sort_order' => 4,
            ],

            // 🇯🇴 JORDAN
            [
                'name' => 'كليك (CliQ Jordan)',
                'sub_name' => 'CliQ الأردن',
                'code' => 'cliq_jordan',
                'country' => 'jordan',
                'country_name' => 'تحويل الأردن',
                'type' => 'manual',
                'currency' => 'JOD',
                'min_amount' => 5.00,
                'max_amount' => 2000.00,
                'fixed_fee' => 0.00,
                'percent_fee' => 0.00,
                'account_number' => 'EMPEROR_CLIQ',
                'note' => 'تحويل فوري عبر نظام كليك الأردني بدون عمولات',
                'instruction' => 'حول عبر اسم المستخدم أو الآيبان ثم أرفق إشعار التحويل.',
                'account_details' => ['cliq_alias' => 'EMPEROR_CLIQ'],
                'is_active' => true,
                'allow_deposit' => true,
                'allow_withdrawal' => true,
                'sort_order' => 5,
            ],
            [
                'name' => 'زين كاش الأردن',
                'sub_name' => 'زين كاش',
                'code' => 'zain_cash_jo',
                'country' => 'jordan',
                'country_name' => 'تحويل الأردن',
                'type' => 'manual',
                'currency' => 'JOD',
                'min_amount' => 5.00,
                'max_amount' => 2000.00,
                'fixed_fee' => 0.00,
                'percent_fee' => 0.00,
                'account_number' => '0791234567',
                'note' => 'شحن فوري ومباشر عبر محفظة زين كاش',
                'instruction' => 'أدخل رقم المحفظة المحول منها ورقم الإشعار.',
                'account_details' => ['wallet_number' => '0791234567'],
                'is_active' => true,
                'allow_deposit' => true,
                'allow_withdrawal' => true,
                'sort_order' => 6,
            ],

            // 🇸🇾 SYRIA
            [
                'name' => 'شام كاش (Sham Cash)',
                'sub_name' => 'شام كاش',
                'code' => 'sham_cash',
                'country' => 'syria',
                'country_name' => 'تحويل سوريا',
                'type' => 'manual',
                'currency' => 'USD',
                'min_amount' => 5.00,
                'max_amount' => 5000.00,
                'fixed_fee' => 0.00,
                'percent_fee' => 0.00,
                'account_number' => '963987654321',
                'note' => 'تحويل مباشر وسريع داخل سوريا بالدولار الأمريكي',
                'instruction' => 'اكتب رقم الحوالة واسم المستلم لسرعة الإيداع في المحفظة.',
                'account_details' => ['account_number' => '963987654321'],
                'is_active' => true,
                'allow_deposit' => true,
                'allow_withdrawal' => true,
                'sort_order' => 7,
            ],

            // 🇸🇦 SAUDI ARABIA
            [
                'name' => 'STC Pay / الراجحي',
                'sub_name' => 'stc pay السعودية',
                'code' => 'stc_pay_sa',
                'country' => 'saudi',
                'country_name' => 'تحويل السعودية',
                'type' => 'manual',
                'currency' => 'SAR',
                'min_amount' => 25.00,
                'max_amount' => 20000.00,
                'fixed_fee' => 0.00,
                'percent_fee' => 0.00,
                'account_number' => '0501234567',
                'note' => 'تحويل فوري من stc pay أو الحسابات البنكية السعودية',
                'instruction' => 'أقل تحويل 25 ريال، اكتب اسم المحول ورقم الحوالة بدقة.',
                'account_details' => ['phone' => '0501234567'],
                'is_active' => true,
                'allow_deposit' => true,
                'allow_withdrawal' => true,
                'sort_order' => 8,
            ],

            // 🇦🇪 UAE
            [
                'name' => 'تحويل الإمارات / درهم',
                'sub_name' => 'درهم إماراتي',
                'code' => 'uae_bank',
                'country' => 'uae',
                'country_name' => 'تحويل الإمارات',
                'type' => 'manual',
                'currency' => 'AED',
                'min_amount' => 25.00,
                'max_amount' => 20000.00,
                'fixed_fee' => 0.00,
                'percent_fee' => 0.00,
                'account_number' => 'AE2503300000124587963',
                'note' => 'تحويل بنكي أو محفظة إماراتية معتمدة',
                'instruction' => 'أقل تحويل 25 درهم، التحويل فوري ومعتمد.',
                'account_details' => ['iban' => 'AE2503300000124587963'],
                'is_active' => true,
                'allow_deposit' => true,
                'allow_withdrawal' => true,
                'sort_order' => 9,
            ],

            // 🇾🇪 YEMEN
            [
                'name' => 'الكريمي إكسبرس (اليمن)',
                'sub_name' => 'الكريمي جوال',
                'code' => 'kuraimi_ye',
                'country' => 'yemen',
                'country_name' => 'تحويل اليمن',
                'type' => 'manual',
                'currency' => 'YER',
                'min_amount' => 5000.00,
                'max_amount' => 2000000.00,
                'fixed_fee' => 0.00,
                'percent_fee' => 0.00,
                'account_number' => '12345678',
                'note' => 'تحويل عبر الكريمي أو ون كاش بالريال اليمني',
                'instruction' => 'أدخل رقم الحوالة ورقم هاتف المرسل بدقة.',
                'account_details' => ['account_number' => '12345678'],
                'is_active' => true,
                'allow_deposit' => true,
                'allow_withdrawal' => true,
                'sort_order' => 10,
            ],

            // 🌐 CRYPTO / USDT
            [
                'name' => 'USDT (TRC-20)',
                'sub_name' => 'USDT TRC20',
                'code' => 'usdt_crypto',
                'country' => 'crypto',
                'country_name' => 'تحويل USDT دولي',
                'type' => 'manual',
                'currency' => 'USD',
                'min_amount' => 5.00,
                'max_amount' => 50000.00,
                'fixed_fee' => 1.00,
                'percent_fee' => 0.00,
                'account_number' => 'TYDzsYbm76DDF4nZp3eM1eF78B99Q1x2Z8',
                'note' => 'تحويل دولي مشفر عبر شبكة ترون TRC20',
                'instruction' => 'حول عملة USDT عبر شبكة TRC20 وأدخل معرف العملية TXID ولقطة الشاشة.',
                'account_details' => ['trc20_address' => 'TYDzsYbm76DDF4nZp3eM1eF78B99Q1x2Z8'],
                'is_active' => true,
                'allow_deposit' => true,
                'allow_withdrawal' => true,
                'sort_order' => 11,
            ],
            [
                'name' => 'Binance Pay (باينانس)',
                'sub_name' => 'BINANCE PAY ID',
                'code' => 'binance_pay',
                'country' => 'crypto',
                'country_name' => 'تحويل USDT دولي',
                'type' => 'manual',
                'currency' => 'USD',
                'min_amount' => 5.00,
                'max_amount' => 50000.00,
                'fixed_fee' => 0.00,
                'percent_fee' => 0.00,
                'account_number' => '891024519',
                'note' => 'دفع فوري بدون رسوم شبكة 0% عبر باينانس باي',
                'instruction' => 'افتح تطبيق Binance Pay وأرسل المبلغ للـ Pay ID الموضح.',
                'account_details' => ['binance_pay_id' => '891024519'],
                'is_active' => true,
                'allow_deposit' => true,
                'allow_withdrawal' => true,
                'sort_order' => 12,
            ],
        ];

        foreach ($methods as $method) {
            PaymentMethod::updateOrCreate(['code' => $method['code']], $method);
        }
    }
}
